# Generated by Django 4.2.1 on 2023-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Song Category')),
            ],
            options={
                'verbose_name': 'SongCategoryModel',
                'verbose_name_plural': 'SongCategoryModels',
            },
        ),
        migrations.CreateModel(
            name='SpotifySongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('song_name', models.CharField(max_length=250, verbose_name='Song Name')),
                ('song_description', models.CharField(max_length=750, verbose_name='Song Description')),
                ('song_category', models.ManyToManyField(related_name='spotify_song_category', to='spotify_base.songcategorymodel')),
            ],
            options={
                'verbose_name': 'SpotifySongModel',
                'verbose_name_plural': 'SpotifySongModels',
            },
        ),
        migrations.CreateModel(
            name='SpotifyPlayListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100, verbose_name='PlayList Name')),
                ('playlist_category', models.ManyToManyField(related_name='spotify_playlist_category', to='spotify_base.songcategorymodel')),
                ('playlist_songs', models.ManyToManyField(related_name='spotify_playlist_songs', to='spotify_base.spotifysongmodel')),
            ],
            options={
                'verbose_name': 'SpotifyPlayList',
                'verbose_name_plural': 'SpotifyPlayLists',
            },
        ),
    ]
