# Generated by Django 4.2.1 on 2023-06-19 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_base', '0002_spotifysongmodel_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifysongmodel',
            name='song_thumbnail',
            field=models.FileField(default=django.utils.timezone.now, verbose_name='Song Thumbnail'),
            preserve_default=False,
        ),
    ]
