# Generated by Django 4.2.1 on 2023-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_base', '0003_spotifysongmodel_song_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifysongmodel',
            name='song_album',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Song Album Name'),
        ),
        migrations.AddField(
            model_name='spotifysongmodel',
            name='song_artist',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Song Artist'),
        ),
        migrations.AlterField(
            model_name='spotifysongmodel',
            name='song_thumbnail',
            field=models.ImageField(blank=True, null=True, verbose_name='Song Thumbnail'),
        ),
    ]
