# Generated by Django 4.2.1 on 2023-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_base', '0004_spotifysongmodel_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifysongmodel',
            name='song_description',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='Song Description'),
        ),
    ]
