# Generated by Django 4.2.1 on 2023-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_base', '0006_remove_spotifysongmodel_song_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifysongmodel',
            name='song_category',
            field=models.ManyToManyField(blank=True, related_name='spotify_song_category', to='spotify_base.songcategorymodel'),
        ),
    ]
